In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [5]:
import pandas as pd
import json

data = '{"employee_name":"james","email":"james@gmail.com",' \
       '"job_profile":[{"title1":"Team Lead","title2":"sr. Developer"}]}'

# Convert JSON string to a Python dictionary
data_dict = json.loads(data)

# Normalize JSON to a flat DataFrame
df = pd.json_normalize(data_dict, 'job_profile', ['employee_name', 'email'])

print(df)

      title1         title2 employee_name            email
0  Team Lead  sr. Developer         james  james@gmail.com

In [6]:
df =pd.read_csv("/kaggle/input/wine-dataset/wine.csv")

In [7]:
df.head()

,Wine,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [13]:
!pip install lxml
!pip install html5lib
!pip install beautifulsoup4
url="https://archive.ics.uci.edu/dataset/53/iris"
df = pd.read_html(url)

Requirement already satisfied: lxml in /usr/local/lib/python3.10/site-packages (5.3.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.0.1 -> 25.0
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: html5lib in /usr/local/lib/python3.10/site-packages (1.1)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.10/site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/site-packages (from html5lib) (0.5.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.0.1 -> 25.0
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/site-packages (4.13.0b3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/site-packages (from beautifulsoup4) (2.6)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/site-packages (from beautifulsoup4) (4.12.2)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.0.1 -> 25.0
[notice] To update, run: pip install --upgrade pip

In [15]:
df

[  Variable Name     Role         Type  \
 0  sepal length  Feature   Continuous
 1   sepal width  Feature   Continuous
 2  petal length  Feature   Continuous
 3   petal width  Feature   Continuous
 4         class   Target  Categorical

                                          Description Units Missing Values
 0                                                NaN    cm             no
 1                                                NaN    cm             no
 2                                                NaN    cm             no
 3                                                NaN    cm             no
 4  class of iris plant: Iris Setosa, Iris Versico...   NaN             no  ,
               File       Size
 0  bezdekIris.data     4.4 KB
 1        iris.data     4.4 KB
 2       iris.names     2.9 KB
 3            Index  105 Bytes]

In [17]:
url = "https://en.wikipedia.org/wiki/Mobile_country_code"
df = pd.read_html(url,match = "country",header=0)
df[0]

,Mobile country code,Country,ISO 3166,Mobile network codes,National MNC authority,Remarks
0,289,A Abkhazia,GE-AB,List of mobile network codes in Abkhazia,NaN,MCC is not listed by ITU
1,412,Afghanistan,AF,List of mobile network codes in Afghanistan,NaN,NaN
2,276,Albania,AL,List of mobile network codes in Albania,NaN,NaN
3,603,Algeria,DZ,List of mobile network codes in Algeria,NaN,NaN
4,544,American Samoa (United States of America),AS,List of mobile network codes in American Samoa,NaN,NaN
...,...,...,...,...,...,...
247,452,Vietnam,VN,List of mobile network codes in the Vietnam,NaN,NaN
248,543,W Wallis and Futuna,WF,List of mobile network codes in Wallis and Futuna,NaN,NaN
249,421,Y Yemen,YE,List of mobile network codes in the Yemen,NaN,NaN
250,645,Z Zambia,ZM,List of mobile network codes in Zambia,NaN,NaN
251,648,Zimbabwe,ZW,List of mobile network codes in Zimbabwe,NaN,NaN